#!/bin/bash
# =============================================================================
# LocalFlow Desktop Agent Installer for macOS/Linux
# =============================================================================
# Usage:
#   curl -fsSL https://your-site.com/api/download?platform=macos | bash
#   # or for Linux:
#   curl -fsSL https://your-site.com/api/download?platform=linux | bash
# =============================================================================

set -e

REPO_URL="https://github.com/jarmen423/whispr_flow_clone_opus.git"
INSTALL_DIR="$HOME/.localflow/localflow"
BIN_DIR="$HOME/.local/bin"
VENV_DIR="$INSTALL_DIR/agent/.venv-whispr"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

step() { echo -e "${CYAN}==>${NC} $1"; }
ok()   { echo -e "${GREEN}   ✓${NC} $1"; }
warn() { echo -e "${YELLOW}   !${NC} $1"; }

# Detect OS
OS="unknown"
if [[ "$OSTYPE" == "darwin"* ]]; then
    OS="macos"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS="linux"
fi

echo ""
echo "============================================"
echo -e "${CYAN}  LocalFlow Desktop Agent Installer${NC}"
echo "============================================"
echo ""

# --- Check Python ---
step "Checking for Python..."
PYTHON_CMD=""
for cmd in python3 python py3; do
    if command -v "$cmd" &>/dev/null; then
        PYTHON_CMD="$cmd"
        break
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo -e "${RED}ERROR: Python is not installed or not in PATH.${NC}"
    echo "Please install Python 3.8+ from https://python.org/downloads/"
    exit 1
fi

PY_VERSION=$("$PYTHON_CMD" --version 2>&1)
ok "Found $PY_VERSION"

# --- Check Git ---
step "Checking for Git..."
if ! command -v git &>/dev/null; then
    echo -e "${RED}ERROR: Git is not installed or not in PATH.${NC}"
    echo "Please install Git from https://git-scm.com/downloads"
    exit 1
fi
ok "Found Git"

# --- Clone or update repo ---
step "Downloading LocalFlow agent..."
if [ -d "$INSTALL_DIR" ]; then
    warn "Existing installation found at $INSTALL_DIR"
    warn "Updating..."
    cd "$INSTALL_DIR"
    git pull --quiet
else
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" --quiet
fi
ok "Agent files ready at $INSTALL_DIR"

# --- Create virtual environment ---
step "Setting up Python environment..."
if [ -d "$VENV_DIR" ]; then
    warn "Virtual environment already exists, reusing..."
else
    "$PYTHON_CMD" -m venv "$VENV_DIR"
fi
ok "Virtual environment created"

# --- Install dependencies ---
step "Installing dependencies (this may take a minute)..."
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet -r "$INSTALL_DIR/agent/requirements.txt"
ok "Dependencies installed"

# --- Create launcher script ---
step "Creating launcher..."
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/localflow-agent" << 'EOF'
#!/bin/bash
# LocalFlow Desktop Agent Launcher
# Auto-generated by install-agent.sh

AGENT_DIR="$HOME/.localflow/localflow/agent"
VENV_ACTIVATE="$AGENT_DIR/.venv-whispr/bin/activate"

cd "$AGENT_DIR"
source "$VENV_ACTIVATE"
python localflow-agent.py "$@"
EOF

chmod +x "$BIN_DIR/localflow-agent"

# Add to PATH if not already present
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    case "$SHELL" in
        */zsh)
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.zshrc"
            ;;
        */bash)
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
            ;;
    esac
    warn "Added $BIN_DIR to your PATH. Run 'source ~/.bashrc' or 'source ~/.zshrc' to use 'localflow-agent' command."
fi
ok "Launcher created at $BIN_DIR/localflow-agent"

# --- Create .desktop entry (Linux only) ---
if [ "$OS" = "linux" ]; then
    step "Creating desktop entry..."
    DESKTOP_DIR="$HOME/.local/share/applications"
    mkdir -p "$DESKTOP_DIR"
    cat > "$DESKTOP_DIR/localflow-agent.desktop" << EOF
[Desktop Entry]
Name=LocalFlow Agent
Comment=LocalFlow Desktop Dictation Agent
Exec=$BIN_DIR/localflow-agent
Type=Application
Terminal=true
Categories=Audio;Utility;
EOF
    ok "Desktop entry created"
fi

# --- Anonymous install ping (no PII, fails silently) ---
curl -s "https://dictate.agentmemorylabs.com/api/install-ping?platform=${OS}" > /dev/null 2>&1 || true

# --- Summary ---
echo ""
echo "============================================"
echo -e "${GREEN}  Installation Complete!${NC}"
echo "============================================"
echo ""
echo "Start the agent:"
echo -e "  ${CYAN}localflow-agent${NC}       (after updating PATH)"
echo -e "  ${CYAN}$BIN_DIR/localflow-agent${NC}  (right now)"
echo ""
echo "Hotkeys (hold to record, release to paste):"
echo "  Alt+L  - Raw dictation"
echo "  Alt+M  - AI formatting"
echo "  Alt+T  - Toggle translation"
echo "  Alt+J  - Format selected text"
echo "  Alt+N  - Cleanup selected text"
echo ""
echo "Failed transcription recovery:"
echo "  Saved failed recordings: $HOME/.localflow/failed-recordings"
echo "  Default retention: 72 hours"
echo ""
warn "The hosted API is used by default. On first run, enter your Groq API key if prompted."
echo ""
