#Requires -Version 5.1
<#
.SYNOPSIS
    LocalFlow Desktop Agent Installer for Windows.

.DESCRIPTION
    Installs the LocalFlow desktop agent with global hotkey support.
    Automatically clones the repository, sets up a Python virtual environment,
    installs dependencies, and creates a launcher.

.EXAMPLE
    # Run directly from the web:
    # irm https://your-site.com/api/download?platform=windows | iex

    # Or run locally:
    .\install-agent.ps1
#>

$ErrorActionPreference = "Stop"

# Configuration
$RepoUrl = "https://github.com/jarmen423/whispr_flow_clone_opus.git"
$InstallDir = "$env:USERPROFILE\.localflow\localflow"
$BinDir = "$env:USERPROFILE\.local\bin"
$VenvDir = "$InstallDir\agent\.venv-whispr"

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)  { Write-Host "   ✓ $msg" -ForegroundColor Green }
function Write-Warn($msg){ Write-Host "   ! $msg" -ForegroundColor Yellow }

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  LocalFlow Desktop Agent Installer" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# --- Check Python ---
Write-Step "Checking for Python..."
$PythonCmd = $null
foreach ($cmd in @("python", "python3", "py")) {
    if (Get-Command $cmd -ErrorAction SilentlyContinue) {
        $PythonCmd = $cmd
        break
    }
}
if (-not $PythonCmd) {
    Write-Host "ERROR: Python is not installed or not in PATH." -ForegroundColor Red
    Write-Host "Please install Python 3.8+ from https://python.org/downloads/"
    Write-Host "Make sure to check 'Add Python to PATH' during installation."
    exit 1
}

$PyVersion = & $PythonCmd --version 2>&1
Write-Ok "Found $PyVersion"

# --- Check Git ---
Write-Step "Checking for Git..."
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: Git is not installed or not in PATH." -ForegroundColor Red
    Write-Host "Please install Git from https://git-scm.com/download/win"
    exit 1
}
Write-Ok "Found Git"

# --- Clone or update repo ---
Write-Step "Downloading LocalFlow agent..."
if (Test-Path $InstallDir) {
    Write-Warn "Existing installation found at $InstallDir"
    Write-Warn "Updating..."
    Set-Location $InstallDir
    git pull --quiet
} else {
    New-Item -ItemType Directory -Path (Split-Path $InstallDir) -Force | Out-Null
    git clone --depth 1 $RepoUrl $InstallDir --quiet
}
Write-Ok "Agent files ready at $InstallDir"

# --- Create virtual environment ---
Write-Step "Setting up Python environment..."
if (Test-Path $VenvDir) {
    Write-Warn "Virtual environment already exists, reusing..."
} else {
    & $PythonCmd -m venv $VenvDir
}
Write-Ok "Virtual environment created"

# --- Install dependencies ---
Write-Step "Installing dependencies (this may take a minute)..."
$Pip = "$VenvDir\Scripts\pip.exe"
& $Pip install --quiet --upgrade pip
& $Pip install --quiet -r "$InstallDir\agent\requirements.txt"
Write-Ok "Dependencies installed"

# --- Create launcher script ---
Write-Step "Creating launcher..."
if (-not (Test-Path $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
}

$LauncherContent = @"
# LocalFlow Desktop Agent Launcher
# Auto-generated by install-agent.ps1

`$AgentDir = "$InstallDir\agent"
`$VenvActivate = "`$AgentDir\.venv-whispr\Scripts\Activate.ps1"

Set-Location `$AgentDir
& `$VenvActivate
python localflow-agent.py
"@

$LauncherPath = "$BinDir\localflow-agent.ps1"
Set-Content -Path $LauncherPath -Value $LauncherContent -Force

# Create .cmd wrapper so user can type 'localflow-agent' without 'powershell'
$CmdWrapper = @"
@echo off
powershell -ExecutionPolicy Bypass -File "%USERPROFILE%\.local\bin\localflow-agent.ps1" %*
"@
Set-Content -Path "$BinDir\localflow-agent.cmd" -Value $CmdWrapper -Force

# Add to PATH if not already present
`$UserPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (`$UserPath -notlike "*`$BinDir*") {
    [Environment]::SetEnvironmentVariable("Path", "`$UserPath;`$BinDir", "User")
    Write-Warn "Added `$BinDir to your PATH. Restart your terminal to use 'localflow-agent' command."
}
Write-Ok "Launcher created at $LauncherPath"

# --- Create Start Menu shortcut ---
Write-Step "Creating Start Menu shortcut..."
$WshShell = New-Object -ComObject WScript.Shell
$StartMenuDir = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\LocalFlow"
if (-not (Test-Path $StartMenuDir)) {
    New-Item -ItemType Directory -Path $StartMenuDir -Force | Out-Null
}
$Shortcut = $WshShell.CreateShortcut("$StartMenuDir\LocalFlow Agent.lnk")
$Shortcut.TargetPath = "powershell.exe"
$Shortcut.Arguments = "-ExecutionPolicy Bypass -File `"$LauncherPath`""
$Shortcut.WorkingDirectory = "$InstallDir\agent"
$Shortcut.IconLocation = "powershell.exe,0"
$Shortcut.Save()
Write-Ok "Start Menu shortcut created"

# --- Anonymous install ping (no PII, fails silently) ---
try {
    Invoke-RestMethod -Uri "https://dictate.agentmemorylabs.com/api/install-ping?platform=windows" -Method GET -TimeoutSec 5 | Out-Null
} catch {
    # Silently ignore ping failures
}

# --- Summary ---
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  Installation Complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "Start the agent:"
Write-Host "  localflow-agent           (after restarting terminal)" -ForegroundColor Cyan
Write-Host "  powershell $LauncherPath  (right now)" -ForegroundColor Cyan
Write-Host ""
Write-Host "Or find it in your Start Menu: LocalFlow > LocalFlow Agent" -ForegroundColor Cyan
Write-Host ""
Write-Host "Hotkeys (hold to record, release to paste):"
Write-Host "  Alt+L  - Raw dictation" -ForegroundColor Gray
Write-Host "  Alt+M  - AI formatting" -ForegroundColor Gray
Write-Host "  Alt+T  - Toggle translation" -ForegroundColor Gray
Write-Host "  Alt+J  - Format selected text" -ForegroundColor Gray
Write-Host "  Alt+N  - Cleanup selected text" -ForegroundColor Gray
Write-Host ""
Write-Host "Failed transcription recovery:"
Write-Host "  Saved failed recordings: $env:USERPROFILE\.localflow\failed-recordings" -ForegroundColor Gray
Write-Host "  Default retention: 72 hours" -ForegroundColor Gray
Write-Host ""
Write-Warn "The hosted API is used by default. On first run, enter your Groq API key if prompted."
Write-Host ""
